services:
  postgres:
    image: postgres:16
    container_name: nest_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: car_value_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: car_value_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
